# Generated by Django 4.2.7 on 2024-01-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_canteen_closing'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='soup',
            field=models.BooleanField(default=False),
        ),
    ]
